/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface3.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
gestion_productos_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		nodo_producto admregistrarproductoofertar_3_arg;
		int abrirsubasta_3_arg;
		char *consultarproducto_3_arg;
		oferta clntofreceroferta_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case admRegistrarProductoOfertar:
		_xdr_argument = (xdrproc_t) xdr_nodo_producto;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) admregistrarproductoofertar_3_svc;
		break;

	case admListarProductosOfertar:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_listaProductos;
		local = (char *(*)(char *, struct svc_req *)) admlistarproductosofertar_3_svc;
		break;

	case abrirSubasta:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) abrirsubasta_3_svc;
		break;

	case cerrarSubasta:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_oferta;
		local = (char *(*)(char *, struct svc_req *)) cerrarsubasta_3_svc;
		break;

	case clntListarProductos:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_listaProductos;
		local = (char *(*)(char *, struct svc_req *)) clntlistarproductos_3_svc;
		break;

	case consultarProducto:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_nodo_producto;
		local = (char *(*)(char *, struct svc_req *)) consultarproducto_3_svc;
		break;

	case consultarDatosProductoActualSubastando:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_nodo_producto;
		local = (char *(*)(char *, struct svc_req *)) consultardatosproductoactualsubastando_3_svc;
		break;

	case clntOfrecerOferta:
		_xdr_argument = (xdrproc_t) xdr_oferta;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) clntofreceroferta_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (gestion_productos, gestion_productos_version_3);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_productos, gestion_productos_version_3, gestion_productos_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (gestion_productos, gestion_productos_version_3, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, gestion_productos, gestion_productos_version_3, gestion_productos_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (gestion_productos, gestion_productos_version_3, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
