/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE3_H_RPCGEN
#define _INTERFACE3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct nodo_producto {
	int codigoProducto;
	char nombre[MAXNOM];
	float valorProducto;
};
typedef struct nodo_producto nodo_producto;

struct nodo_cliente_oferta {
	int identificacionClnt;
	char nombre[MAXNOM];
	char apellido[MAXNOM];
	char correo[MAXNOM];
	int telefono;
};
typedef struct nodo_cliente_oferta nodo_cliente_oferta;

struct oferta {
	nodo_producto objProducto;
	nodo_cliente_oferta objCliente;
	float valorPuja;
};
typedef struct oferta oferta;

struct listaProductos {
	nodo_producto productos[5];
};
typedef struct listaProductos listaProductos;

#define gestion_productos 0x20000003
#define gestion_productos_version_3 3

#if defined(__STDC__) || defined(__cplusplus)
#define admRegistrarProductoOfertar 1
extern  bool_t * admregistrarproductoofertar_3(nodo_producto *, CLIENT *);
extern  bool_t * admregistrarproductoofertar_3_svc(nodo_producto *, struct svc_req *);
#define admListarProductosOfertar 2
extern  listaProductos * admlistarproductosofertar_3(void *, CLIENT *);
extern  listaProductos * admlistarproductosofertar_3_svc(void *, struct svc_req *);
#define abrirSubasta 3
extern  bool_t * abrirsubasta_3(int *, CLIENT *);
extern  bool_t * abrirsubasta_3_svc(int *, struct svc_req *);
#define cerrarSubasta 4
extern  oferta * cerrarsubasta_3(void *, CLIENT *);
extern  oferta * cerrarsubasta_3_svc(void *, struct svc_req *);
#define clntListarProductos 5
extern  listaProductos * clntlistarproductos_3(void *, CLIENT *);
extern  listaProductos * clntlistarproductos_3_svc(void *, struct svc_req *);
#define consultarProducto 6
extern  nodo_producto * consultarproducto_3(char **, CLIENT *);
extern  nodo_producto * consultarproducto_3_svc(char **, struct svc_req *);
#define consultarDatosProductoActualSubastando 7
extern  nodo_producto * consultardatosproductoactualsubastando_3(void *, CLIENT *);
extern  nodo_producto * consultardatosproductoactualsubastando_3_svc(void *, struct svc_req *);
#define clntOfrecerOferta 8
extern  bool_t * clntofreceroferta_3(oferta *, CLIENT *);
extern  bool_t * clntofreceroferta_3_svc(oferta *, struct svc_req *);
extern int gestion_productos_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define admRegistrarProductoOfertar 1
extern  bool_t * admregistrarproductoofertar_3();
extern  bool_t * admregistrarproductoofertar_3_svc();
#define admListarProductosOfertar 2
extern  listaProductos * admlistarproductosofertar_3();
extern  listaProductos * admlistarproductosofertar_3_svc();
#define abrirSubasta 3
extern  bool_t * abrirsubasta_3();
extern  bool_t * abrirsubasta_3_svc();
#define cerrarSubasta 4
extern  oferta * cerrarsubasta_3();
extern  oferta * cerrarsubasta_3_svc();
#define clntListarProductos 5
extern  listaProductos * clntlistarproductos_3();
extern  listaProductos * clntlistarproductos_3_svc();
#define consultarProducto 6
extern  nodo_producto * consultarproducto_3();
extern  nodo_producto * consultarproducto_3_svc();
#define consultarDatosProductoActualSubastando 7
extern  nodo_producto * consultardatosproductoactualsubastando_3();
extern  nodo_producto * consultardatosproductoactualsubastando_3_svc();
#define clntOfrecerOferta 8
extern  bool_t * clntofreceroferta_3();
extern  bool_t * clntofreceroferta_3_svc();
extern int gestion_productos_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_producto (XDR *, nodo_producto*);
extern  bool_t xdr_nodo_cliente_oferta (XDR *, nodo_cliente_oferta*);
extern  bool_t xdr_oferta (XDR *, oferta*);
extern  bool_t xdr_listaProductos (XDR *, listaProductos*);

#else /* K&R C */
extern bool_t xdr_nodo_producto ();
extern bool_t xdr_nodo_cliente_oferta ();
extern bool_t xdr_oferta ();
extern bool_t xdr_listaProductos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE3_H_RPCGEN */
