/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface3.h"

bool_t
xdr_nodo_producto (XDR *xdrs, nodo_producto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->codigoProducto))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valorProducto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_cliente_oferta (XDR *xdrs, nodo_cliente_oferta *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->identificacionClnt))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->apellido, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->correo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->telefono))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_oferta (XDR *xdrs, oferta *objp)
{
	register int32_t *buf;

	 if (!xdr_nodo_producto (xdrs, &objp->objProducto))
		 return FALSE;
	 if (!xdr_nodo_cliente_oferta (xdrs, &objp->objCliente))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valorPuja))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_listaProductos (XDR *xdrs, listaProductos *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->productos, 5,
		sizeof (nodo_producto), (xdrproc_t) xdr_nodo_producto))
		 return FALSE;
	return TRUE;
}
