/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 20

struct nodo_administrador {
	char login[MAXNOM];
	char contrasenia[MAXNOM];
	int identificacionAdm;
	char nombre[MAXNOM];
	char apellido[MAXNOM];
};
typedef struct nodo_administrador nodo_administrador;

#define gestion_administrador 0x20000002
#define gestion_administrador_version_2 2

#if defined(__STDC__) || defined(__cplusplus)
#define registrarAdministrador 1
extern  bool_t * registraradministrador_2(nodo_administrador *, CLIENT *);
extern  bool_t * registraradministrador_2_svc(nodo_administrador *, struct svc_req *);
#define enviarDatosSesionAdministrador 2
extern  bool_t * enviardatossesionadministrador_2(nodo_administrador *, CLIENT *);
extern  bool_t * enviardatossesionadministrador_2_svc(nodo_administrador *, struct svc_req *);
extern int gestion_administrador_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrarAdministrador 1
extern  bool_t * registraradministrador_2();
extern  bool_t * registraradministrador_2_svc();
#define enviarDatosSesionAdministrador 2
extern  bool_t * enviardatossesionadministrador_2();
extern  bool_t * enviardatossesionadministrador_2_svc();
extern int gestion_administrador_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_administrador (XDR *, nodo_administrador*);

#else /* K&R C */
extern bool_t xdr_nodo_administrador ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
