/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface2.h"
#include <string.h>

nodo_administrador administradores[5];
int posRegistrar=0;
int existeAdministrador(nodo_administrador cliente){
	for(int i=0 ; i<posRegistrar ; i++){
		if(strcmp(administradores[i].login,cliente.login) == 0){
			return 1;
		}
	}
	return 0;
}
bool_t *
registraradministrador_2_svc(nodo_administrador *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Invocando registrar administrador");
	printf("\n identificacion del administrador %d" ,argp->identificacionAdm);
	if(posRegistrar<5){
		if(existeAdministrador(*argp) == 0){
			administradores[posRegistrar]=*argp;
			printf("\n RESPUESTA DEL SERVIDOR:");
			printf("\n Administrador registrado!");
			printf("\n **************************");
			result=TRUE;
			posRegistrar++;
		}
		else{
			printf("\n RESPUESTA DEL SERVIDOR:");
			printf("\n ERROR, el administrador ya se encuentra registrado...");
			printf("\n **************************");
			result=FALSE;
		}
	}
	else{
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n No se pudo registrar el administrador.");
		printf("\n ************************************");
		return FALSE;
	}
	
	return &result;
}

bool_t *
enviardatossesionadministrador_2_svc(nodo_administrador *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Invocando iniciar sesion");
	printf("\n Login %s" ,argp->login);
	printf("\n Contrasenia %s",argp->contrasenia);
	for(int i = 0 ; i<5 ; i++){
		if(strcmp(administradores[i].login,argp->login) == 0){
			if(strcmp(administradores[i].contrasenia,argp->contrasenia) == 0){
				printf("\n RESPUESTA DEL SERVIDOR:");
				printf("\n Existe el administrador");
				printf("\n ************************");
				result=TRUE;
				return &result;
			}
		}
	}	
	result=FALSE;
	if(result==FALSE){
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n No existe el administrador");
		printf("\n ***********************");
	}

	return &result;
}