/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "interface1.h"
#include <string.h>

nodo_cliente clientes[5];
int posRegistrar=0;
int existeCliente(nodo_cliente cliente){
	for(int i=0 ; i<posRegistrar ; i++){
		if(strcmp(clientes[i].login,cliente.login) == 0){
			return 1;
		}
	}
	return 0;
}
bool_t *
registrarcliente_1_svc(nodo_cliente *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Invocando registrar registrar cliente");
	printf("\n identificacion del cliente %d" ,argp->identificacionClnt);
	if(posRegistrar<5){
		if(existeCliente(*argp) == 0){
			clientes[posRegistrar]=*argp;
			printf("\n RESPUESTA DEL SERVIDOR:");
			printf("\n Cliente registrado!");
			printf("\n **************************");
			result=TRUE;
			posRegistrar++;
		}
		else{
			printf("\n RESPUESTA DEL SERVIDOR:");
			printf("\n ERROR, el cliente ya se encuentra registrado...");
			printf("\n ************************************");
			result=FALSE;
		}
	}
	else{
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n No se pudo registrar el cliente.");
		printf("\n ************************************");
		return FALSE;
	}
	
	return &result;
}

bool_t *
enviardatossesioncliente_1_svc(nodo_cliente *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n Invocando iniciar sesion");
	printf("\n Login %s" ,argp->login);
	printf("\n Contrasenia %s",argp->contrasenia);
	for(int i = 0 ; i<5 ; i++){
		if(strcmp(clientes[i].login,argp->login) == 0){
			if(strcmp(clientes[i].contrasenia,argp->contrasenia) == 0){
				printf("\n RESPUESTA DEL SERVIDOR:");
				printf("\n Existe el cliente");
				printf("\n ************************");
				result=TRUE;
				return &result;
			}
		}
	}	
	result=FALSE;
	if(result==FALSE){
		printf("\n RESPUESTA DEL SERVIDOR:");
		printf("\n No existe el cliente");
		printf("\n ***********************");
	}

	return &result;
}